let chansons = [
  "A l'ombre des maris",
  "A l'ombre du cœur de ma mie",
  "A la goutte d'or",
  "A la place Maubert",
  "A Mireille",
  "A mon frère revenant d'Italie",
  "A Paris dans chaque Faubourg",
  "Altesse",
  "(L') amandier",
  "(L') amour est passé près de vous",
  "(Les) amoureux des bancs publics",
  "(Les) amours d'antan",
  "(L') ancêtre",
  "(L') andropause",
  "(L') antéchrist",
  "(L') arc en ciel d'un quart d'heure",
  "(L') assassinat",
  "Au bois de mon cœur",
  "Au grand café",
  "Auprès de mon arbre",
  "Avoir un bon copain",
  "Ballade à la lune",
  "(La) ballade des cimetières",
  "Ballade des dames du temps jadis",
  "(La) ballade des gens qui sont nés quelque part",
  "Le bateau de pêche",
  "Bécassine",
  "Belleville - Ménilmontant",
  "(Le) bistrot",
  "(Le) blason",
  "Bonhomme",
  "Boulevard du temps qui passe",
  "(Le) bout du coeur",
  "Brave Margot",
  "(Le) bricoleur",
  "(Le) bulletin de santé",
  "(La) cane de Jeanne",
  "Carcassonne",
  "(Les) casseuses",
  "(Le) cauchemar",
  "Ce n'est pas tout d'être mon père",
  "Celui qui a mal tourné",
  "Ceux qui ne pensent pas comme nous",
  "(La) chanson du hérisson",
  "Chanson pour l'auvergnat",
  "Chansonnette à celle qui reste pucelle",
  "(Le) chapeau de Mireille",
  "(La) chasse aux papillons",
  "(Les) châteaux de sable",
  "Clairette et la fourmi",
  "(Le) cocu",
  "Colombine",
  "Comme hier",
  "Comme une sœur",
  "(La) complainte des filles de joie",
  "Concurrence déloyale",
  "(Les) copains d'abord",
  "Corne d'Aurochs",
  "(Les) croquants",
  "Cupidon s'en fout",
  "Dans l'eau de la claire fontaine",
  "Dans l'eau de la claire fontaine (version M. LeForestier)",
  "(Les) deux oncles",
  "Dieu si il existe",
  "(Le) discours des fleurs",
  "Don Juan",
  "Le drapeau noir flotte sur la marmite",
  "Élégie à un rat de cave",
  "Embrasse-les tous",
  "(L') enterrement de Paul Fort",
  "(L') enterrement de Verlaine",
  "Entre l'Espagne et l'Italie",
  "Entre la rue Didot et la rue de Vanves",
  "(L') épave",
  "(Le) fantôme",
  "(La) femme d'Hector",
  "Fernande",
  "(La) fessée",
  "(Le) fiacre",
  "(La) file indienne",
  "(La) fille à cent sous",
  "Fleur bleue",
  "(Le) fossoyeur",
  "(Les) funérailles d'antan",
  "Gastibelza",
  "Germaine Tourangelle",
  "(Le) gorille",
  "(Le) grand chêne",
  "(Le) grand Pan",
  "Grand-Père",
  "(Le) grand vicaire",
  "(La) guerre de 14-18",
  "Hécatombe",
  "Heureux qui comme Ulysse",
  "Histoire de faussaire",
  "Honte à qui peut chanter",
  "Il n'a pas eu la chaude-pisse",
  "Il n'y a d'honnête que le bonheur (Viens)",
  "Il n'y a pas d'amour heureux",
  "Il suffit de passer le pont",
  "(Les) illusions perdues",
  "(L') inestimable sceau",
  "J'ai rendez-vous avec vous",
  "Je me suis fait tout petit",
  "Je rejoindrai ma belle",
  "Je suis swing",
  "Je suis un voyou",
  "Jean rentre au village",
  "Jeanne",
  "Jeanne Martin",
  "Jehan l'Advenu",
  "(Une) jolie fleur",
  "Lèche-cocu",
  "(La) légende de la nonne",
  "(La) légion d'honneur",
  "(Les) lilas",
  "(La) maîtresse d'école",
  "Maman, Papa",
  "(La) marche nuptiale",
  "(La) marguerite",
  "(La) marine",
  "Marinette",
  "Marquise",
  "(Le) mauvais sujet repenti",
  "(La) mauvaise herbe",
  "(La) mauvaise réputation",
  "Méchante avec de jolis seins",
  "(Le) mécréant",
  "(Le) mécréant repenti",
  "Mélanie",
  "(La) messe au pendu",
  "Misogynie à part",
  "(Le) modeste",
  "Mon père me donne cent sous",
  "Montélimar",
  "Mourir pour des idées",
  "(Le) mouton de panurge",
  "(Le) moyenâgeux",
  "(Le) myosotis",
  "(Le) nombril des femmes d'agents",
  "(La) non-demande en mariage",
  "(La) nymphomane",
  "(Les) oiseaux de passage",
  "Oncle Archibald",
  "(L') orage",
  "(L') orphelin",
  "Oui et non",
  "P... de toi",
  "(Le) parapluie",
  "(Les) passantes",
  "(Le) passéiste",
  "(Les) patriotes",
  "Pauvre Martin",
  "(Le) pêcheur",
  "Pénélope",
  "Pensée des morts",
  "(Le) père Noël et la petite fille",
  "(Le) petit cheval",
  "Le petit fils d'Oedipe",
  "(Le) petit joueur de flûteau",
  "Petit oiseau",
  "Philistins",
  "(Le) pince-fesses",
  "Places de Paris",
  "(Le) pluriel",
  "(Le) pornographe",
  "Pour me rendre à mon bureau",
  "(La) première fille",
  "(La) prière",
  "(La) princesse et le croque-notes",
  "(Le) progrès",
  "Quand les cons sont braves",
  "Quand un vicomte",
  "(Les) quat'z'arts",
  "(Les) quatre bacheliers",
  "Quatre-vingt-quinze pour cent",
  "Les radis",
  "(La) religieuse",
  "Retouches à un roman d'amour de quatre sous",
  "Retouches à un roman d'amour de quatre sous (version M. LeForestier)",
  "(Le) revenant",
  "(Les) ricochets",
  "Rien à jeter",
  "(Le) Roi",
  "(Le) roi boiteux",
  "(La) ronde des jurons",
  "(La) rose la bouteille et la poignée de main",
  "(La) route aux quatre chansons",
  "S'faire enculer",
  "(Les) sabots d'Hélène",
  "Sale petit bonhomme",
  "Saturne",
  "Sauf le respect que je vous dois",
  "(Le) sceptique",
  "Si le Bon Dieu l'avait voulu",
  "Si seulement elle était jolie",
  "Stances à un cambrioleur",
  "Supplique pour être enterré à la plage de Sète",
  "Sur la mort d'une cousine de sept ans",
  "Tant qu'il y a des Pyrénées",
  "Tempête dans un bénitier",
  "(Le) temps ne fait rien à l'affaire",
  "(Le) temps passé",
  "Terre",
  "(Le) testament",
  "(La) tondue",
  "Tonton Nestor",
  "Tout est au duc",
  "(La) traîtresse",
  "Trompe la mort",
  "(Les) trompettes de la renommée",
  "Tu t'en iras les pieds devant",
  "(Le) vent",
  "Vénus Callipyge",
  "(Le) verger du roi Louis",
  "Verlaine",
  "(Le) vieux Léon",
  "(Le) vieux Normand",
  "(Le) vin",
  "(Le) vingt-deux septembre",
  "(La) visite"
]